### ISSUE TITLE
Basic Blocks (page, link, image)

### ISSUE THREAD

**Issue by bschlagel** [hyperlink-academy/minilink#10]
A few things to finish up with the initial block set:

- [x] screenshots / previews for card blocks
- [x] cursor pointer for linked cards (should be consistent with external link blocks)
- [x] properly render headers in linked card previews

**Comment by bschlagel** [comment]
If rendering full card previews is tricky, maybe for now we can just make a generic card preview that uses the current theme colors…

**Comment by jaredpereira** [comment]
Okay, done!
