### ISSUE TITLE
Selection and focus

### ISSUE THREAD

**Issue by bschlagel** [hyperlink-academy/minilink#13]
A bunch of things related to selecting text and blocks, focus state, etc.

**Done**
- [x] clicking in between blocks should still focus them [CELINE]
- [x] block select state can be unclear — for non-text blocks, do we want a difference between navigating through blocks and selecting them? right now they look not fully selected, but are still deletable, which is odd; also see #29 - pages in particular are *too* easy to delete in the 'selected by keyboard' case! ideal would be the same prompt to confirm delete (but would need to handle multi-select)
- [x] when blocks are selected, clicking in a blank area on the card should deselect + focus last block; clicking bg outside card should also deselect
- [x] #16
- [x] with multiple blocks selected, left/up should deselect and go to beginning of selection; right/down should deselect and go to end of selection
- [x] in first text block, up arrow should go to beginning; in last text block, down arrow should go to end
- [x] if I select all text in a block (triple click or cmd-a), clicking in the block again should deselect
- [x] selecting multiple blocks and hitting delete should delete all those blocks
- [x] when dragging to select blocks, sometimes it skips blocks
- [x] after deleting blocks, should focus to previous block before first in deleted selection (current = nothing focused)
- [x] bug: if I drag to multiselect text blocks, only the dragged portion of the first block is actually selected (and shows as selected text)…doesn't happen w/ keyboard select, only click + drag
- [x] clicking existing linked card: should focus at end of last block, not beginning of first block

**Comment by bschlagel** [comment]
@jaredpereira added a couple lil ones here

**Comment by jaredpereira** [comment]
For focusing the existing linked card, I'm thinking just making it not focus into a block unless it's a brand new card. Is that fine?

**Comment by cyberspaceline** [comment]
>  clicking existing linked card: should focus at end of last block, not beginning of first block

are we sure about it? if the card it really long it'll scroll the whole thing to the bottom
