### ISSUE TITLE
Deleting header block can glitch out (mobile)

### ISSUE THREAD

**Issue by bschlagel** [hyperlink-academy/minilink#14]
In mobile, deleting a header block causes that block to become weird and unclickable, refreshing page brings back the header as if you never deleted it

@cyberspaceline still seeing this? Not sure I see it though there are other issues w/ deleting blocks on mobile (we should figure out deletion for #5 )

**Comment by jaredpereira** [comment]
I think this has been fixed. Let me know if anyone still runs into it.
