### ISSUE TITLE
when text is selected, up / down arrows should go to beginning / end of highlighted selection area

### ISSUE THREAD

**Issue by jaredpereira** [hyperlink-academy/minilink#16]

**Comment by jaredpereira** [comment]
Didn't quite mean to make this an issue but oh well. Testing, this doesn't seem to be the default behavior in browsers at least. Up/down ignores selection and just goes to the start/end of the textarea you're in. Obsidian I can see has the other behavior.

**Comment by jaredpereira** [comment]
Google docs does the browser style

**Comment by bschlagel** [comment]
Ah k testing more yeah looks like start/end if single line, or prev/next line from start of selection if multi-line…that works for me! (Tried w/ Notion and Coda too, looks like Coda is the only one that does it how Obsidian does (iA Writer doesn't so not like a Mac thing!)

**Comment by jaredpereira** [comment]
Okay cool, just going with the browser default handling then!
