### ISSUE TITLE
Set up shorter doc urls (ids)

### ISSUE THREAD

**Issue by bschlagel** [hyperlink-academy/minilink#18]
Instead of long uuids for docs (e.g. `a318cb8c-0165-4715-8e78-d08730ed0e03`)…

Let's make em short and sweet! Maybe…16 chars?

**Comment by jaredpereira** [comment]
Okay, so while we have some flexibility on this, we've decided not to bother w/ it for now! Keeping it as uuids keeps everything pretty simple!
