### ISSUE TITLE
Set per-document metadata for nice share links

### ISSUE THREAD

**Issue by bschlagel** [hyperlink-academy/minilink#19]
Goal: nice doc preview rendering both in linked docs and external social media links.

- Update doc titles based on first text/header block
- Maybe second block = description?
- Image (optional) should be first image in doc

**Comment by jaredpereira** [comment]
Okay I added the page title. For the image should I try to render the card preview we have for the card blocks as the open graph image? I it's a better vibe than just pulling the image from the doc.

**Comment by bschlagel** [comment]
Nice! We should either get rid of the generic description too ("tiny interlinked social documents") or try pulling from like the second text block…maybe better to just not have it since it might be not what you want; could be a setting later.

For image, I'd be into the screenshot style like it renders for external links (showing not just the card itself but bg as well)…looks nice in my test leaflet page!

**Comment by jaredpereira** [comment]
Yeah BG def important! Will try it out.

**Comment by bschlagel** [comment]
@jaredpereira just FYI was testing w/ these and the image seemed to generate within like 2-3 seconds:

- https://opengraph.dev/panel?url=https://leaflet.pub/78171781-3e50-487a-8fca-debb61529239
- https://www.opengraph.xyz/url/https%3A%2F%2Fleaflet.pub%2F78171781-3e50-487a-8fca-debb61529239

(But seeing "og:description missing" warning which makes me think maybe it's expected / better to add even it it may sometimes be not quite right)

**Comment by bschlagel** [comment]
Also very tiny thing but in some of the examples above w/ common social platforms the title is cut off, may wanna try a different aspect ratio — no idea why but looks like 1.91:1 is common, e.g. 1200 x 630px (maybe a standard set by facebook or something)

**Comment by jaredpereira** [comment]
Okay, tweaked the aspect ratio and added description metadata, closing this now!
