### ISSUE TITLE
Share Links (read + edit)

### ISSUE THREAD

**Issue by bschlagel** [hyperlink-academy/minilink#2]
Leaflet docs should have a share button with two options in a dropdown:

- Readonly share link, for people to view the doc
- Edit link, to grant collaborators full edit access to the doc

Subtasks:

- [ ] button icons for both read (publish) and edit (collab) links

**Related re: permissions:**
Whatever permission systems we do here should be play nice with future extensions for scoped permissions and different roles.

**Comment by bschlagel** [comment]
Which link should be the default i.e. if you copy directly from browser address bar? 

With no permissions / accounts the default being editable for everyone (as it works now with no separate share links) might be most straightforward, with "publish" as a special additional action. But could that make it too easy to accidentally share an editable link?

**Comment by bschlagel** [comment]
@jaredpereira couple little things! Tiny one = the publish link still has an extra `:`

Also, need to hide / prevent editing of theme settings for the publish read-only link!

**Comment by jaredpereira** [comment]
Cool fixed
