### ISSUE TITLE
Highlight settings: a few small issues

### ISSUE THREAD

**Issue by bschlagel** [hyperlink-academy/minilink#25]
Handful of lil things:

- [x] In the highlight color settings, newly selected colors do not save (they revert to the defaults after a second)
- [x] Also, "highlight 1" color displays incorrectly in the color picker
- [x] Copy-pasted blocks with highlight seem to all paste with the 3rd highlight color applied, even if the original blocks have different highlight colors
- [x] A polish thing: I think there's an extra shadow around the color picker bar in toolbar we can remove…and _maybe_ can make it like 2px wider?

**Comment by bschlagel** [comment]
@cyberspaceline added a few things here!

**Comment by cyberspaceline** [comment]
@bschlagel can you screenshot the extra shadow? or maybe just explain again? I'm not sure i'm seeing what you mean :T

**Comment by bschlagel** [comment]
The little color bar next to highlight icon has a white border and also a grey (shadow?) border around that; I think just the white border is fine and the grey looks noisy that's all!On Jul 6, 2024, at 2:21 PM, celine ***@***.***> wrote:﻿
@bschlagel can you screenshot the extra shadow? or maybe just explain again? I'm not sure i'm seeing what you mean :T

**Comment by bschlagel** [comment]
Or instead of white maybe text color as border would be best for matching the toolbar!

**Comment by cyberspaceline** [comment]
ah i see i see! i need both because if the card color is light, then only the grey border will show and if it the card is dark, then only the light will show... but maybe border color will work, i'll give it a shot!
