### ISSUE TITLE
Keyboard block selection sometimes selects an extra block

### ISSUE THREAD

**Issue by bschlagel** [hyperlink-academy/minilink#26]
If I'm in a text block and select with shift+down til the end of the block, then shift+down _again_, it selects two more text blocks (not just the next one as expected). Same with shift+up for previous block(s).

**Comment by jaredpereira** [comment]
Fixed in [0197939](https://github.com/hyperlink-academy/minilink/commit/0197939195f8352f3782ab1568113fa3d26530cf)
