### ISSUE TITLE
Placeholder catch-all for polish items!

### ISSUE THREAD

**Issue by bschlagel** [hyperlink-academy/minilink#27]
Not sure if I'll have time to make nice separate issues for these, so for now a misc bucket it is… @cyberspaceline @jaredpereira feel free to edit / extract to separate issues as needed if I don't get to it first! These are I think all low priority (not critical for alpha):

SUPER HARD ACTUALLY
- [ ] accessibility: we should make headers the correct h1, h2 etc. elements (not just 'p' with styling)

FURTHER Q's
- [ ] focus state: sometimes when cursor is in a text block, and I scroll so cursor's out of view, it seems to try to scroll me back to where the cursor is (same if I switch apps then re-focus, it scrolls back up to cursor)…may need to make manual scroll position override til you actually start typing again

CELINE WIP
- [x] block selection: I think I'd like a subtle bg for selected blocks, a tiny bit more than just the bar on the side…suggestion: make bg color `color-mix(in oklab,rgb(var(--primary)),rgb(var(--bg-card)) 90%)`
- [x] empty block (i.e. a single blank line between blocks) shows as a huge gap in linked card previews
- [x] Add labels to theme and share buttons (or at least tooltips)  
- [x] layout: also need to account for global side buttons (e.g. theme / share) and card buttons (e.g. close) at all breakpoints in calculating card max width so buttons don't get squashed off screen
- [x] layout: at med width (like 960 to 1300) card feels too narrow…maybe make full width and *only* narrow if > 1 card open so you can see two-up?
- [x] focus state: clicking outside page unfocuses text input but doesn't hide toolbar
- [x] focus state: clicking just above first block (top padding above all blocks) focus to end of doc; ideally should move that padding from 'blocks' wrapper to first block so it always focuses first block…low priority if annoying though
- [x] inline links should open in new window (like link blocks)
- [x] highlights: color 1 preview is inaccurate in settings (correct elsewhere in the toolbar)
- [x] theme settings: clicking hex code maybe shouldn't toggle color picker (makes the hex code hard to double click to copy)

**Comment by cyberspaceline** [comment]
>  empty block (i.e. a single blank line between blocks) shows as a huge gap in linked card previews
@bschlagel can you explain more? I don't think i understand!

**Comment by cyberspaceline** [comment]
>  highlights: color 1 preview is inaccurate in settings (correct elsewhere in the toolbar)
i changed it to show that the color is "default" but in the settings it will show as white. I know its not perfect but its really hard to get the right color. if its not too big a deal is the bandaid good enough?
<img width="369" alt="image" src="https://github.com/hyperlink-academy/minilink/assets/4051426/eb4c6dc7-cf43-4c17-98ea-efdf205c9249">

**Comment by bschlagel** [comment]
> > empty block (i.e. a single blank line between blocks) shows as a huge gap in linked card previews
> 
> @bschlagel can you explain more? I don't think i understand!

Oh yeah just in `cardBlockPreview` it renders empty blocks w/ a div that has a `min-h-9` inside it that makes it look like ~4 empty lines instead of one in the lil preview

**Comment by cyberspaceline** [comment]
>  focus state: sometimes when cursor is in a text block, and I scroll so cursor's out of view, it seems to try to scroll me back to where the cursor is (same if I switch apps then re-focus, it scrolls back up to cursor)…may need to make manual scroll position override til you actually start typing again

Can you also clarify this? You mention that is happens when you switch apps. When else does it happen?

**Comment by bschlagel** [comment]
@cyberspaceline not a huge deal, this one; it may have been happening more on mobile and better now. But also seeing when I switch to another sub-page in a doc. For a doc longer than one page height: 

- switching apps: focus last text block, scroll to top, toggle to another app and back and you're scrolled back down to where text is focused (maybe not an issue just a little )
- within doc: focus last text block, scroll to top, click a linked page…it opens the page but also scrolls the first page back to the bottom, *and* then fails to scroll over and focus input on the newly opened card (as I test more this latter feels more actually buggy)

**Comment by cyberspaceline** [comment]
checked off most of the stuff! The focus issue isn't resolved yet, but I'll spin that out into another issue
