### ISSUE TITLE
Non-text blocks are difficult to delete

### ISSUE THREAD

**Issue by cyberspaceline** [hyperlink-academy/minilink#29]
Link blocks and card blocks are difficult to remove. They can be removed if you simply delete them, but this is rather undiscoverable. 

Some solutions include
- Adding explicit delete buttons to these block types 
- Adding sub toolbar variants for them that include a delete button 
- Make selecting nontext blocks more intuitive, they can be deleted that way 

For now, Celine make a stopgap delete button on the blocks, but we should revist for a more elegant solution

**Comment by bschlagel** [comment]
I like Jared's idea of selected block toolbar options. Should work for single or multi-selected blocks, and have options to delete, move up/down arrows…later maybe cut/copy/paste as well.

The tricky thing UI-wise I think is not adding the toolbar items, but on mobile having a way to select blocks at all! Which is TBD, see: #5 

For now the "x" to remove block seems useful for delete, but def would still be nice to be able to move blocks around, both on mobile and desktop!

**Comment by bschlagel** [comment]
@cyberspaceline I'm into the delete/nevermind confirmation on delete page! Small tweaks that could be nice:

- de-focusing the block or clicking any other block could be equivalent to "nevermind"
- would be nice to prompt this on delete from keyboard as well! (the tricky thing there may be handling when multiple blocks are selected and you hit delete…no rush on this if complicated)

**Comment by cyberspaceline** [comment]
Defocusing the block now clears the are you sure state! The second thing is a good bit more lift, and this was only a stop gap anyway, so I'm gonna leave it!

**Comment by bschlagel** [comment]
Closing as _good enough_ for now; we can revisit the broader case of block selection and manipulation (esp on mobile) later!
