### ISSUE TITLE
Focus State scrolls Card to cursor on reload

### ISSUE THREAD

**Issue by cyberspaceline** [hyperlink-academy/minilink#31]
focus state: sometimes when cursor is in a text block, and I scroll so cursor's out of view, it seems to try to scroll me back to where the cursor is (same if I switch apps then re-focus, it scrolls back up to cursor)…may need to make manual scroll position override til you actually start typing again #31

### Further details from Brendan
not a huge deal, this one; it may have been happening more on mobile and better now. But also seeing when I switch to another sub-page in a doc. For a doc longer than one page height:

- switching apps: focus last text block, scroll to top, toggle to another app and back and you're scrolled back down to where text is focused (maybe not an issue just a little )
- within doc: focus last text block, scroll to top, click a linked page…it opens the page but also scrolls the first page back to the bottom, and then fails to scroll over and focus input on the newly opened card (as I test more this latter feels more actually buggy)

**Comment by jaredpereira** [comment]
Okay, all of these should be fixed!
