### ISSUE TITLE
Block selection glitch with read-only docs

### ISSUE THREAD

**Issue by bschlagel** [hyperlink-academy/minilink#32]
Issue with the new selected block background highlighting — viewing a read-only doc, it's possible to drag to select blocks, but it's somehow only showing the bg highlight in front of block content (like once dragged, the actual block content is hidden).

What should happen: no block select highlighting if viewing a read-only doc, *but* you should be able to select the text as normal readonly web page text (I think previously there was a different issue where drag to select text wasn't working at all).

**Comment by jaredpereira** [comment]
Should be fixed! Didn't deal w/ the block select bg highlighting on top  of text, just prevented block selecting on read-only. My guess for that issue is that there's a difference in z-indexing between the readonly rendered textblock and the editable one.
