### ISSUE TITLE
A few glitches adding inline links

### ISSUE THREAD

**Issue by bschlagel** [hyperlink-academy/minilink#33]
Various things:

- [x] with selected text, if I click the link button, it no longer appears visually selected
- [x] on mobile at least, the "add a link" input is not auto-focused
- [x] after enter/submit button to add link, cursor should be at end of link (currently text is de-focused)
- [x] really should get in cmd-k for adding link, would make it much nicer & I think ppl expect it!

**Comment by jaredpereira** [comment]
Oki! Done!
