### ISSUE TITLE
LEAFLET POLISH INBOX!

### ISSUE THREAD

**Issue by bschlagel** [hyperlink-academy/minilink#34]
Various small things to adjust or fix :) Some I'm unsure about; comment to discuss or clarify if needed!

- [ ] when selecting blocks via keyboard, should scroll up or down in the page with the selection

DONE
- [x] editor toolbar: toggling text formatting like bold/italic/strikethrough, button state doesn't update right away on mobile (via Jase) (But Celine is unable to reproduce)
- [x] hitting return w/ cursor at beginning of a header block ideally moves the header down but does *not* change to a paragraph; similarly w/ delete, it should delete the empty prev block but leave you still w/ a header I think
- [x] clicking the toolbar itself will unfocus what you're typing. Maybe take a hint from the keepFocus function in textBlockTypeButton
- [x] disable link submit if field is empty 
- [x] inline links: maybe should have a hover color
- [x] page preview blocks: spacing's a little too narrow between title and second text line (preview on left, not tiny text in rendered card) - only on mobile it seems!
- [x] new doc: also should auto-focus text on new doc creation, so you can immediately start typing!
- [x] editor toolbar: also sometimes when clicking toolbar buttons the selected text gets visually deselected (no longer selection highlight, but is still in fact selected)
- [x] maybe we should default the first block in a page to h1? (suggestion from Sam to make it more clear how to give pages titles)
- [x] in a blank page the "write something" placeholder text overlaps before the cursor a tiny bit
- [x] scrolling: maybe we should lose the scroll animation? makes it weird and laggy when holding up/down arrows to nav through a long doc (on desktop)
- [x] images: maybe add slightly rounded corners to match other blocks and cards?

mmmm.... idk
- [ ] inline links *inside* card preview blocks prob should not be independently clickable

**Comment by cyberspaceline** [comment]
I'd say no to inline link hover color! the internet doesn't do that usually and i'd have to calculate a new color value to achieve this which i think its too much for now lol

**Comment by cyberspaceline** [comment]
> - [ ] editor toolbar: toggling text formatting like bold/italic/strikethrough, button state doesn't update right away on mobile (via Jase) (But Celine is unable to reproduce)

wasn't able to reproduce this... has anyone else seen it?
