### ISSUE TITLE
When a text string is highlighted with keyboard shortcut, it overwrites clipboard contents

### ISSUE THREAD

**Issue by bschlagel** [hyperlink-academy/minilink#38]
If I copy text A from somewhere, then before I paste into a doc I highlight text B in the doc, when I paste, I get the full block that contains text B — seems the act of highlighting replaces text A on the clipboard somehow.

Seems this ONLY happens when using the highlight shortcut (cmd-ctrl-H), and not when clicking the toolbar…couldn't find indication of that being like a weird mac global 'copy paragraph' shortcut or something so idk!

**Comment by jaredpereira** [comment]
Fixed, was an issue with the logic for triggering the copy command on keyboard presses
