### ISSUE TITLE
Lists copied from Leaflet paste in text editors with extra linebreaks

### ISSUE THREAD

**Issue by bschlagel** [hyperlink-academy/minilink#43]
If I copy a list from Leaflet, and paste into a text editor like Obsidian or iA Writer, some list items paste with extra line breaks between them.

Not sure if it's an issue more with the html to markdown pipeline, or the way we're structuring lists in the first place.

The extra new lines aren't between *every* list item, for example…

a list that looks like this in a test Leaflet:

```
-   hey it's some more list testing!
-   can I collapse the children of this block?
    -   first child
    -   middle child
        -   another!
    -   youngest child
    -   more family
        -   I'm the auntie
        -   I'm the uncle
        -   I'm the grandpa
```

pastes like this:

```
-   hey it's some more list testing!

-   can I collapse the children of this block?

    -   first child

    -   middle child
        -   another!

    -   youngest child

    -   more family

        -   I'm the auntie
        -   I'm the uncle
        -   I'm the grandpa
```

**Comment by bschlagel** [comment]
Gah damn just noticed list items now have an extra two spaces between the `-` and the text. I tweaked the default list marker and indent but idk why there are extra spaces *after* the list marker…

**Comment by jaredpereira** [comment]
Okay, fixed this by modifying the parsed markdown list to always be tight. If we ever need to support loose lists (idk why we would but perhaps) we shall have to revist.
