### ISSUE TITLE
Clicking bottom of doc should focus last visible item, even if nested in a list

### ISSUE THREAD

**Issue by bschlagel** [hyperlink-academy/minilink#44]
Currently "focus last text block when clicked below" only works for non-list text blocks.

If the last block is a nested list item, it focuses the parent block, which is odd and makes it hard to add to the list.

This behavior I think makes sense if the list is collapsed (and only the top level parent is visible) but if children are visible (i.e. list toggled open, as default) the last child should be focused.

**Comment by cyberspaceline** [comment]
fixed!
