### ISSUE TITLE
Copy and paste

### ISSUE THREAD

**Issue by bschlagel** [hyperlink-academy/minilink#6]
As with #1 copying and pasting should work seamlessly both in text areas, and across blocks in a document. (NB: ofc "cut" should work here as well!)

Inside text areas:
- [ ] Also, selected text is not overwritten on paste (e.g. if I have text `One` selected and paste `Two` I should just have `Two` but end up with `TwoOne`)
- [ ] After pasting a substring into another text block, the cursor goes to end of block when it should go to end of just-pasted string!
- [x] Inline formatting should be copied properly
- [x] Text should be able to be pasted into other apps (at least plaintext; ideally markdown for formatted text I think?)

Across blocks:
- [ ] Multi-selected blocks should be copy/cut and pastable into other pages and docs
- [ ] Copying / pasting blocks with the cursor in an empty block should prob replace that block vs. adding after and leaving the one empty block
- [x] If multiple blocks are cut/copied and pasted into another app e.g. external text editor, at least the text should copy as expected (other blocks TBD…could ignore or e.g. just copy titles)
- [x] Should paste in the correct order no matter which direction selected
- [x] All formatting of text blocks should be maintained
- [x] After pasting, should focus to end of last block (not first)

**Comment by jaredpereira** [comment]
Need to work on Cut! It has some the additional complexity of needing to handle deleting the non-text blocks

**Comment by bschlagel** [comment]
I think copy-pasting from rich text / html (?) sometimes fails; not sure if it's the html tags but e.g. the leaflet section of [our homepage](https://hyperlink.academy/) only some parts are copied…

**Comment by bschlagel** [comment]
Noticing earlier that sometimes copy-paste from a Leaflet to external app also sometimes fails (with just text blocks). Can't repro now though! Will see if I run into this again…it was weird, if I clicked into a block and cmd-a to select, it failed, but if I nav with keyboard then cmd-a it worked.

**Comment by bschlagel** [comment]
BTW found this clipboard inspector useful for testing: https://evercoder.github.io/clipboard-inspector/

I'm seeing one issue where copy-pasting text blocks to external editors doesn't work — I think b/c they don't handle HTML content which is the only content copied.

If it's possible to add *both* HTML and plaintext to the clipboard data object when copied maybe that'd help here? (Obsidian for example doesn't work, but iA Writer does I assume just b/c they handle converting html to plaintext on paste…)

**Comment by cyberspaceline** [comment]
Splitting remaining stuff into a new isssue and closing this one #37
