### ISSUE TITLE
Editing toolbar

### ISSUE THREAD

**Issue by bschlagel** [hyperlink-academy/minilink#8]
Most things here are working! A couple remaining to dos:

- [x] wire up block adder
- [x] inline link - needs to focus input (otherwise pasting overwrites the highlighted text); sometimes clicking the link text input field fails to focus; hitting enter should submit; turn off printing the text string range
- [x] highlight
- [x] strikethrough
- [x] move block adder into separate submenu, available is focused into an empty block

**Comment by jaredpereira** [comment]
okay block adder added! I think we still need to fully map out the state transitions for the toolbar, when it goes into block adder state and when to get out of it, and how that relates to header v paragraph, but can split that out into a seperate issue when it comes up!
