### ISSUE TITLE
Delete page

### ISSUE THREAD

**Issue by bschlagel** [hyperlink-academy/minilink#9]
- [x] rm delete option on root card
- [x] Wire up the "delete page" button in page menu.
- [ ] Also wire up the "undo" in toast after deletion (dependency: #1)

**Comment by bschlagel** [comment]
I think delete page shouldn't show for the top level page? Or…do we want to enable deleting a whole doc? If so what happens?

**Comment by cyberspaceline** [comment]
> I think delete page shouldn't show for the top level page? Or…do we want to enable deleting a whole doc? If so what happens?

yup lets just get rid of the card options on the root page!

**Comment by cyberspaceline** [comment]
it's a little too easy to delete cards with the keyboard but for now, its fine, we close these
